### ISSUE TITLE
Can't start BearTrap

### ISSUE THREAD

**Issue by hudene** [chrisbdaemon/BearTrap#2]
I'm a linux newbie...I don't know if I'm doing this right. 

I used git clone https://github.com/chrisbdaemon/Bear/Trap to get the repository.

When I try to start it up, this is what I get

root@raspberrypi:/opt/BearTrap# sudo ruby bear_trap.rb -c config.yml
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- getopt/long (LoadError)
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from bear_trap.rb:29:in `<main>'

I have no idea what this means, any help would be greatly appreciated

**Comment by chrisbdaemon** [comment]
Sorry for not responding sooner, you need to install the getopt gem.

Theres a note for it in the readme.

Run this:
```
gem install getopt
```
