### ISSUE TITLE
TCPPort crashes under nmap scan

### ISSUE THREAD

**Issue by tbennett6421** [chrisbdaemon/beartrap#4]
Once I enable a TCPPort and run an nmap scan from another machine the program crashes.
nmap 10.1.1.1

------------------------------------------------------------------------------------------------------------
tbennett@fserver:~/beartrap$ sudo ruby bear_trap.rb -c config.yml -d
Trying to load trigger: {"type"=>"TCPPort", "port"=>3389, "address"=>"0.0.0.0"}
Loading /home/tbennett/beartrap/lib/Trigger/TCPPortTrigger.rb
/home/tbennett/beartrap/lib/Trigger/TCPPortTrigger.rb loaded successfully
Checking parameters for #<TCPPortTrigger:0x00000002a2b618>
Parameters verified for #<TCPPortTrigger:0x00000002a2b618>
Trying to load trigger: {"type"=>"FTP", "banner"=>"BearTrap-ftpd Service ready"}
Loading /home/tbennett/beartrap/lib/Trigger/FTPTrigger.rb
/home/tbennett/beartrap/lib/Trigger/FTPTrigger.rb loaded successfully
Checking parameters for #<FTPTrigger:0x00000002a647d8>
Parameters verified for #<FTPTrigger:0x00000002a647d8>
Loading /home/tbennett/beartrap/lib/AlertHandler/CommandlineAlertHandler.rb
/home/tbennett/beartrap/lib/AlertHandler/CommandlineAlertHandler.rb loaded successfully
Checking parameters for #<CommandlineAlertHandler:0x00000002a83a48>
Parameters verified for #<CommandlineAlertHandler:0x00000002a83a48>
Binding TCP socket to: 0.0.0.0:3389
Binding FTP server to 0.0.0.0:21
Created thread for #<TCPServer:0x00000002a82ff8>
Created thread for #<TCPServer:0x00000002a83160>
Command: /sbin/iptables -A INPUT -s 10.1.1.102 -j DROP
/home/tbennett/beartrap/lib/AlertHandler/CommandlineAlertHandler.rb:55:in `handle_alert': undefined method `success?' for nil:NilClass (NoMethodError)
	from bear_trap.rb:86:in `block in got_alert'
	from bear_trap.rb:85:in `each'
	from bear_trap.rb:85:in `got_alert'
	from /home/tbennett/beartrap/lib/Trigger/TCPPortTrigger.rb:63:in `block (2 levels) in set_trigger'
	from /home/tbennett/beartrap/lib/Trigger/TCPPortTrigger.rb:51:in `loop'
	from /home/tbennett/beartrap/lib/Trigger/TCPPortTrigger.rb:51:in `block in set_trigger'

**Comment by tbennett6421** [comment]
The exact same thing happens when i attempt to telnet to that port

**Comment by chrisbdaemon** [comment]
Have you had a chance to retest this with the commit you just pushed up?

**Comment by tbennett6421** [comment]
Yes this appears to have been fixed with the latest commit. Thanks

**Comment by chrisbdaemon** [comment]
Thanks so much for catching my mistake and submitting a fix for it. I was just getting settled in to figure it out myself when the pull request came in.

Let me know if you need anything else.
